import type { Metadata } from "next";
import "./globals.css";
import { Urbanist, DM_Sans, Outfit } from "next/font/google";

const urbanist_init = Urbanist({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-urbanist",
  display: "swap",
});
const dmSans_init = DM_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-dm_sans",
  display: "swap",
});
const outfit_init = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-outfit",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist_init.variable} ${outfit_init.variable} ${dmSans_init.variable}`}
      >
        <div id="modal-level-1" className="!z-[2] fixed top-0 left-0" />
        <div id="modal-level-2" className="!z-[3] fixed top-0 left-0" />
        <div id="modal-level-3" className="!z-[4] fixed top-0 left-0" />
        <div id="modal-level-4" className="!z-[5] fixed top-0 left-0" />
        <div id="modal-level-5" className="!z-[6] fixed top-0 left-0" />
        <div className="!z-[1] relative">{children}</div>
      </body>
    </html>
  );
}
